name: "CI"

on:
  push:
    branches-ignore:
      - "main"
defaults:
  run:
    shell: bash

jobs:
  Build:
    name: "Build / Test"
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@master

      - name: Generate Config
        run: ./scripts/generate-config.sh
        shell: sh
        env:
          API_GATEWAY_ID: ${{ secrets.API_GATEWAY_ID }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          REGION: ${{ secrets.REGION }}
          USER_POOL_ID: ${{ secrets.USER_POOL_ID }}
          APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
          IDENTITY_POOL_ID: ${{ secrets.IDENTITY_POOL_ID }}

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install
        run: npm ci

      - name: Build 🔧
        run: npm run build --if-present

      - name: Test
        run: npm test
        env:
          CI: true
